#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Heat                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ### Local thermostat defaults ###
  temp_max: "25"

  ##### DO NOT CHANGE THIS #####
  addon_climate_heat: "true"
  ##############################

climate:
  - id: !extend thermostat_embedded
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_deadband: ${heat_deadband} ${temp_units}
    heat_overrun: ${heat_overrun} ${temp_units}
#    sensor: ${sensor}
    heat_action:
      - switch.turn_on: relay_${heater_relay}
    default_preset: "none"
    preset:
      - name: none
        default_target_temperature_low: ${preset_home_temperature} ${temp_units}
        mode: "off"
      - name: home
        default_target_temperature_low: ${preset_home_temperature} ${temp_units}
        mode: "heat"
      - name: sleep
        default_target_temperature_low: ${preset_sleep_temperature} ${temp_units}
        mode: "heat"
      - name: away
        default_target_temperature_low: ${preset_away_temperature} ${temp_units}
        mode: "heat"
      - name: activity
        default_target_temperature_low: ${preset_activity_temperature} ${temp_units}
        mode: "heat"

packages:
  climate_heat_package: !include esphome/nspanel_esphome_addon_climate_heat.yaml
...
